#!/bin/bash
#
# Copyright (c) 2020 Seagate Technology LLC and/or its Affiliates
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# For any questions about this software or licensing,
# please email opensource@seagate.com or cortx-questions@seagate.com.


PIP=pip3.6 
POST_INSTALL_REQUIREMENTS=/opt/seagate/cortx/utils/conf/requirements.txt

# rpm utility passes additional parameter to indicate whether it is a fresh
# install, un-install or upgrade. For this script un-install or upgrade are
# the valid scenarios. 0 means un-install and 1 means upgrade.
# Remove required packages only when uninstall
if [ $1 == 0 ]
then
    sudo $PIP uninstall --yes -r $POST_INSTALL_REQUIREMENTS
fi
